title:             Gavin Shavey
email:             gavinshavey@gmail.com
description:       Personal Website
author:            Gavin Shavey
baseurl:           ""
url:               "http://gshav.github.io"

# Social Profiles
twitter_username:  GavinShavey
github_username:   gshav
facebook_username: gavin.shavey

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
